In [7]:
# Print returns arguments to console
print('fit a model with', 11, 'variables')


# Integer math
3 + 5


fit a model with 11 variables


8

In [8]:
# Integer math
3 + 5

8

In [12]:
# Strings can be concatenated
"hello" + " " + "world"

'hello world'

In [23]:
# List are defined with []
x = [3,4,5]
x

[3, 4, 5]

In [28]:
# List can be concatenated together
y = [4, 9, 7]
x + y

# The above returns [3, 4, 5, 4, 9, 7] since they are concatenated rather than added 

# If you want to add the values together you could do this
added = [y[i] + x[i] for i in range(len(y))]
print(added)


[7, 13, 12]


In [13]:
# Another way we can get the added listed together is using numpy
import numpy as np

# np.array() function to define x and y which are one-dimensional arrays or vectors
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

x + y

array([ 7, 13, 12])

In [30]:
# Numpy matrices are typically represented as two-dimensional arrays and vectors as one dimensional
# A two dimensional array looks like this

x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [31]:
x.ndim

# The output of 2 indicates this is a two-dimensional aray

2

In [32]:
x.dtype

# This returns integer since we passed in exclusively integer if we passed in values with decimals then we would have obtained an array of floating point numbers

dtype('int32')

In [33]:
np.array([[1, 2], [3.1, 4]]).dtype

dtype('float64')

In [ ]:
# You can get documentation to display with a function by attached a ? to the end of a function
np.array?

In [35]:
# Using the above means we can make an integer array to floating type by changing the dtype optional parameter
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [36]:
# If we use the shape attribute we can find out its number of rows and columns
x.shape

(2, 2)

In [38]:
# We can sum all the elements of an array by calling like x.sum() it automatically passes x into the first argument

x = np.array([1, 2, 3, 4])
x.sum()

# You could get the same result by calling np.sum(x)
np.sum(x)

10

In [42]:
# You can call reshape() to return a new array with the same elements but a different shape
# Using \n indicates a new line
x = np.array([1, 2, 3, 4, 5, 6])
print("Begigning x:\n", x)
x_reshape = x.reshape((2,3))
print("Reshaped x:\n", x_reshape)

Begigning x:
 [1 2 3 4 5 6]
Reshaped x:
 [[1 2 3]
 [4 5 6]]


In [46]:
# You can access array elements of x_reshape like this

x_reshape[1, 2]

6

In [48]:
# We can modify the top left element [0, 0] in our array
print("x before we modify x_shape:\n" , x)
print("x_reshape before we modify x_reshape:\n", x_reshape)
x_reshape[0, 0] = 9
print("x_reshape after we modify its top left element [0, 0]:\n", x_reshape)
print("x after we modify the top left element [0, 0]: \n", x)

x before we modify x_shape:
 [9 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[9 2 3]
 [4 5 6]]
x_reshape after we modify its top left element [0, 0]:
 [[9 2 3]
 [4 5 6]]
x after we modify the top left element [0, 0]: 
 [9 2 3 4 5 6]


In [ ]:
# Modifying x_shape also modified x because the two object occupy the same space in memory

# We can modify an element of an array but you cannot modify an element of a tuple indicated by () because they are immutable

my_tuple = (3, 4, 5)
my_tuple[1] = 8

# This will generate an error

In [53]:
# Some attributes that can be useful when dealing with arrays
# The shape attribute contains its dimension and it is always a tuple
# The ndim attribute yields its number of dimensions
# T provides an arrays transpose

x_reshape, x_reshape.shape, x_reshape.ndim, x_reshape.T

(array([[9, 2, 3],
        [4, 5, 6]]),
 (2, 3),
 2,
 array([[9, 4],
        [2, 5],
        [3, 6]]))

In [55]:
# You can easily apply functions to arrays such as sqrt or squaring the elements
# Reminder x = [9 2 3 4 5 6]
np.sqrt(x)

array([3.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [56]:
x**2

array([81,  4,  9, 16, 25, 36])

In [ ]:
# You can generate random data and that can be done through the np.random.normal() function that generates a vector of random normal variables

np.random.normal?

In [67]:
x = np.random.normal(size=50)
x

array([-1.24986049,  0.18746741, -0.31774795,  1.29805534, -1.98789185,
       -0.04886085,  1.28681948,  1.06578599,  1.48096508, -2.30430622,
        0.38394336, -0.60934589, -2.56424265, -0.97911938,  0.54093219,
       -0.20950857, -0.84632441, -0.08809037,  0.40996678, -0.54407995,
        1.42950617, -0.67086975,  1.17620287, -0.70821739, -2.25078839,
        1.21732558,  2.33140444,  0.79954116, -0.05841957, -0.50832523,
       -0.09082427, -0.08257849, -1.43354545,  0.32387041, -0.29851132,
       -1.87224044, -0.65173881, -0.83572431, -0.75495637,  0.01635996,
        1.30970456, -0.46851686,  0.00411118, -0.05741798, -1.25264576,
       -1.22534995, -1.19733685, -0.7163491 , -0.44070535,  0.62118608])

In [70]:
y = x + np.random.normal(scale=1, loc=50, size=50)
y

array([48.19364375, 51.33932877, 49.67253972, 51.08389286, 47.83549755,
       50.45946993, 50.89620805, 50.36151554, 51.0736573 , 47.13278707,
       51.14575924, 49.14599287, 45.64147293, 49.77518438, 49.42307599,
       48.39552174, 49.51982359, 48.64478956, 49.17576679, 49.12583725,
       51.13224231, 49.13025038, 52.91890516, 48.67823708, 49.70426553,
       50.55522393, 53.18054642, 52.09810698, 49.93685449, 48.4433621 ,
       51.71885494, 51.90109814, 49.63181632, 52.26601636, 50.51938303,
       48.67668526, 48.35536184, 48.81692866, 48.79199123, 50.21042956,
       51.77093505, 48.45981457, 50.47481266, 49.04769412, 49.52025222,
       49.55183443, 47.43661758, 48.62182409, 48.82082904, 50.42004859])

In [71]:
# the np.corrcoef() function computes the correlation matrix between x and y

np.corrcoef(x, y)

array([[1.        , 0.77000387],
       [0.77000387, 1.        ]])

In [72]:
# To follow along in the book we can use random seeds to generate the same data
rng = np.random.default_rng(1303)
print(rng.normal(scale=5, size=2))
rng2 = np.random.default_rng(1303)
print(rng2.normal(scale=5, size=5))

[ 4.09482632 -1.07485605]
[  4.09482632  -1.07485605 -10.15364596   1.13406146  -4.14030566]


In [87]:
# np.mean(), np.var(), and np.std() can be used to computer the mean, variance, and standard deviation of arrays. Available as methods on the arrays

rng = np.random.default_rng(3)
y = rng.standard_normal(10)

print("array y: \n", y, "\nMean of Y:",  np.mean(y), "\nVar of Y: ", np.var(y), "\nStandard Deviation of Y: " , y.std())

array y: 
 [ 2.04091912 -2.55566503  0.41809885 -0.56776961 -0.45264929 -0.21559716
 -2.01998613 -0.23193238 -0.86521308  3.32299952] 
Mean of Y: -0.1126795190952861 
Var of Y:  2.7243406406465125 
Standard Deviation of Y:  1.6505576756498128


In [88]:
# You can apply functions to rows and columsn of a mtrix

x = rng.standard_normal((10,3))
x

array([[ 0.22578661, -0.35263079, -0.28128742],
       [-0.66804635, -1.05515055, -0.39080098],
       [ 0.48194539, -0.23855361,  0.9577587 ],
       [-0.19980213,  0.02425957,  1.54582085],
       [ 0.54510552, -0.50522874, -0.18283897],
       [ 0.54052513,  1.93508803, -0.26962033],
       [-0.24355868,  1.0023136 , -0.88645994],
       [-0.29172023,  0.88253897,  0.58035002],
       [ 0.0915167 ,  0.67010435, -2.82816231],
       [ 1.02130682, -0.95964476, -1.66861984]])

In [92]:
# Arrays are row-major ordered so 0 refers to its rows
x.mean(0)

array([ 0.15030588,  0.14030961, -0.34238602])