In [59]:
import numpy as np

a = np.array([[1,1,1,1,1], [1,0,0,0,1], [1,0,9,0,1], [1,0,0,0,1], [1,1,1,1,1]] )
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [60]:
b = np.zeros((5,5), dtype='int32')
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [61]:
b.ndim

2

In [62]:
b.shape

(5, 5)

In [63]:
b[2,2] = 9
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 9 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [64]:
b[:, [0,4]] = 1
b[[0, 4], :] = 1
b[2,2] = 9
print(b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [65]:
b[:,0] = 1
b[:,4] = 1
b[0,:] = 1
b[4,:] = 1

print(b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [66]:
b = np.ones((5,5), dtype='int32')
print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [67]:
b[1:-1,1:-1] = 0
b[2,2] = 9
print(b)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [93]:


mat = np.arange(1,31)
mat = mat.reshape(6,5)
#mat[[12, 13, 18, 20]]
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [96]:
# Index rows 2-4 then index columns 0-2. End digit is exclusive
mat[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [102]:
mat[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [130]:
mat[[0,4,5] , 3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])